; Luz nocturna. Con horas fijas en vez de ubicación: de 20:00 a 21:00 pasa
; poco a poco a luz cálida y de 7:00 a 8:00 vuelve a la normal.
[general]
temp-day=6500
temp-night=4000
fade=1
dusk-time=20:00-21:00
dawn-time=07:00-08:00
adjustment-method=randr
